# Generated by Django 3.0.5 on 2020-05-01 11:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmcsJobId', models.CharField(max_length=20)),
                ('jobId', models.CharField(blank=True, max_length=20, null=True)),
                ('jobTitle', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('minExp', models.IntegerField(default=0)),
                ('maxExp', models.IntegerField(default=0)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('jobDesc', models.TextField()),
                ('description', models.TextField()),
                ('is_listed', models.BooleanField(default=False)),
                ('noOfApplies', models.IntegerField(blank=True, default=0)),
                ('shortLists', models.IntegerField(blank=True, default=0)),
                ('selections', models.IntegerField(blank=True, default=0)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
