# Generated by Django 3.0.5 on 2020-05-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200501_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='remvedBy',
            new_name='removedBy',
        ),
    ]
