# Generated by Django 3.0.5 on 2020-05-04 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200504_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='removeDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
