# Generated by Django 3.0.5 on 2020-04-29 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workEmail', models.CharField(blank=True, max_length=50)),
                ('companyName', models.CharField(blank=True, max_length=255)),
                ('companyURL', models.TextField(blank=True, max_length=2083)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('verificationURL', models.TextField(blank=True, max_length=2083)),
                ('user_verified', models.BooleanField(blank=True, default=False)),
                ('companyLogo', models.ImageField(blank=True, upload_to='Employer/<django.db.models.fields.CharField>/')),
                ('profileImage', models.ImageField(blank=True, upload_to='Employer/<django.db.models.fields.CharField>/')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
