# Generated by Django 3.0.5 on 2020-05-03 05:44

import accounts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=200, null=True)),
                ('companyURL', models.TextField(default=None, max_length=2083, null=True)),
                ('companyLogo', models.ImageField(default=None, null=True, upload_to=accounts.models.user_directory_path_company)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, default=0)),
                ('workEmail', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('verificationToken', models.TextField(blank=True, max_length=2083)),
                ('user_verified', models.BooleanField(blank=True, default=False)),
                ('admin_verified', models.IntegerField(blank=True, default=0)),
                ('action', models.CharField(default='newRequest', max_length=30)),
                ('admin_comments', models.CharField(blank=True, max_length=100)),
                ('profileImage', models.ImageField(upload_to=accounts.models.user_directory_path_profile)),
                ('approvalDate', models.DateTimeField(blank=True, null=True)),
                ('removeRequestDate', models.DateTimeField(blank=True, null=True)),
                ('removeApprovalDate', models.DateTimeField(blank=True, null=True)),
                ('request_for', models.CharField(blank=True, default='activation', max_length=20)),
                ('posts', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('requestFor', models.CharField(max_length=20)),
                ('adminReqAction', models.CharField(max_length=10)),
                ('actionDate', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 3, 11, 14, 23, 405652))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
