# Generated by Django 3.0.5 on 2020-04-29 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='companyLogo',
            field=models.ImageField(upload_to='Employer/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='companyName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='companyURL',
            field=models.TextField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(upload_to='Employer/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workEmail',
            field=models.CharField(max_length=50),
        ),
    ]
