# Generated by Django 3.0.5 on 2020-04-30 04:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200429_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='companyLogo',
            field=models.ImageField(upload_to=accounts.models.user_directory_path_company),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(upload_to=accounts.models.user_directory_path_profile),
        ),
    ]
