# Generated by Django 3.0.5 on 2020-05-03 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200503_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactions',
            name='actionDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 3, 13, 31, 1, 302341)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.IntegerField(default=0),
        ),
    ]
