# Generated by Django 3.0.5 on 2020-04-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200430_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='verificationURL',
            new_name='verificationToken',
        ),
    ]
