# Generated by Django 3.0.5 on 2020-04-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200430_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='action',
            field=models.CharField(default='newRequest', max_length=30),
        ),
    ]
