# Generated by Django 3.0.5 on 2020-05-03 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200503_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactions',
            name='actionDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 3, 15, 0, 10, 974003)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
