# Generated by Django 3.0.5 on 2020-05-03 09:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200503_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactions',
            name='actionDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 3, 15, 12, 48, 296701)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.CompanyMaster'),
        ),
    ]
