# Generated by Django 3.0.5 on 2020-04-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_admin_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approvalDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
