# Generated by Django 3.0.5 on 2020-04-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_approvaldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='request_for',
            field=models.CharField(blank=True, default='activation', max_length=20),
        ),
    ]
