# Generated by Django 3.0.5 on 2020-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_request_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admin_verified',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
