# Generated by Django 3.0.5 on 2020-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200430_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='removeApprovalDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='removeRequestDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
