# Generated by Django 3.0.5 on 2020-05-04 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200504_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='livePosts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='adminactions',
            name='actionDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 4, 14, 21, 2, 763440)),
        ),
    ]
