# Generated by Django 3.0.5 on 2020-04-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200430_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
