# Generated by Django 3.0.5 on 2020-05-01 04:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('requestFor', models.CharField(max_length=20)),
                ('adminAction', models.CharField(max_length=10)),
                ('actionDate', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 10, 3, 16, 518152))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
