# Generated by Django 3.0.5 on 2020-05-01 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_adminactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminactions',
            old_name='adminAction',
            new_name='adminReqAction',
        ),
        migrations.AlterField(
            model_name='adminactions',
            name='actionDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 10, 9, 11, 130012)),
        ),
    ]
