# Generated by Django 3.0.5 on 2020-05-04 11:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0005_auto_20200504_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('blacklisted', models.BooleanField(blank=True, default=False)),
                ('noOfApplies', models.IntegerField(blank=True, default=0)),
                ('noOfOffers', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rejectDate', models.DateTimeField(blank=True, null=True)),
                ('shortlistDate', models.DateTimeField(blank=True, null=True)),
                ('selectionDate', models.DateTimeField(blank=True, null=True)),
                ('workflowLevel', models.CharField(blank=True, default='apply', max_length=12)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidates.Candidate')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Listing')),
            ],
        ),
    ]
